"""Real-time streaming audio generation: FlowDiT + CoDiCodec `decode_next()`.

Generates audio chunk-by-chunk at runtime: one CoDiCodec chunk
(~32_768 samples = ~683 ms at 48 kHz) per generation step. Each chunk is
streamed through `EncoderDecoder.decode_next()` straight to the system audio
output via `sounddevice`.

Per-chunk pipeline
------------------
    1.  Sliding-window prefix latent context (in raw codec space).
    2.  `cfm_sample()` -> `block_size` new latent tokens (one chunk).
    3.  `CodecWrapper.decode_next_chunk()` -> ~32_768 stereo samples.
    4.  Push to a thread-safe `AudioBuffer`.
    5.  `sounddevice.OutputStream` callback pulls fixed-size frames -> speakers.

Architectural differences vs. the example CAM realtime script
-------------------------------------------------------------
*   FlowDiT is block-causal: every chunk is generated by re-running the full
    transformer over the prefix + the new chunk's `block_size` tokens. There
    is no KV cache; instead we keep a *latent buffer* of past tokens and slide
    a fixed-length window across it (`--context-chunks`).
*   The denoising loop is rectified-flow CFM (`flow.model.cfm.sample`), not
    score-based diffusion. Solvers are `euler` and `heun`. The "temperature"
    knob simply rescales the predicted velocity each ODE step (smaller
    temperature -> stronger drift toward the data manifold; larger ->
    more variance).
*   Initial unconditional context is just an empty prefix `[1, 0, latent_dim]`,
    optionally seeded with a small amount of frozen Gaussian noise the model
    can latch onto via `--seed-scale`.
*   `--seed`, `s`/`S`/`x`/`X` keyboard actions reseed Python/Torch/NumPy RNGs
    and reset the codec's streaming state via `CodecWrapper.reset_streaming()`.

Example
-------
    python -m flow.realtime \
        --ckpt ./runs/v3_okachihuali/last.pt \
        --use-ema \
        --device mps \
        --solver euler \
        --nfe 4 \
        --context-chunks 32 \
        --temperature 1.0
"""

from __future__ import annotations

import argparse
import collections
import math
import os
import random
import select
import sys
import termios
import threading
import time
import tty
from pathlib import Path
from typing import List, Optional

import numpy as np
import torch

try:
    import sounddevice as sd
except ImportError:  # pragma: no cover
    print("ERROR: sounddevice is required. Install with: pip install sounddevice")
    sys.exit(1)

try:
    import soundfile as sf
except ImportError:  # pragma: no cover
    sf = None  # optional

from .codec_wrapper import CodecConfig, CodecWrapper
from .config import ModelConfig
from .model.dit import FlowDiT
from .model.ema import EMA
from .utils import best_device, block_causal_mask, get_logger

logger = get_logger("flow.realtime")


def _parse_summary_vec(s: str, n: int, name: str) -> List[float]:
    """Parse a CLI summary-control argument as either a single scalar (broadcast
    to length n) or a comma-separated list of exactly n floats.
    """
    parts = [p.strip() for p in str(s).split(",") if p.strip() != ""]
    if len(parts) == 1:
        return [float(parts[0])] * n
    if len(parts) != n:
        raise ValueError(
            f"--{name}: expected a scalar or {n} comma-separated floats, got {len(parts)}"
        )
    return [float(p) for p in parts]


# --------------------------------------------------------------------------- #
# Model loading (mirrors flow/sample.py but factored out for reuse).
# --------------------------------------------------------------------------- #

def load_model(ckpt_path: str, device: torch.device, *, use_ema: bool) -> FlowDiT:
    """Load a FlowDiT checkpoint. Optionally swap in EMA weights (recommended)."""
    sd = torch.load(ckpt_path, map_location="cpu", weights_only=False)
    if "config" not in sd or "model" not in sd["config"]:
        raise RuntimeError(
            f"checkpoint {ckpt_path} has no 'config.model' field; cannot rebuild architecture"
        )
    model_cfg = ModelConfig(**sd["config"]["model"])
    model = FlowDiT(
        latent_dim=model_cfg.latent_dim,
        block_size=model_cfg.block_size,
        dim=model_cfg.dim,
        n_layers=model_cfg.n_layers,
        n_heads=model_cfg.n_heads,
        head_dim=model_cfg.head_dim,
        mlp_mult=model_cfg.mlp_mult,
        cond_dim=model_cfg.cond_dim,
        max_seq_len=model_cfg.max_seq_len,
        dropout=0.0,  # no dropout at inference
    )
    if use_ema:
        ema_state = sd.get("ema")
        if ema_state is None:
            raise RuntimeError(f"--use-ema set but {ckpt_path} has no 'ema' field")
        ema = EMA(model, decay=0.0)
        ema.load_state_dict(ema_state)
        ema.copy_to(model)
        logger.info("Loaded EMA weights from %s", ckpt_path)
    else:
        if "model" not in sd:
            raise RuntimeError(f"checkpoint {ckpt_path} has no 'model' field")
        model.load_state_dict(sd["model"])
        logger.info("Loaded raw (non-EMA) weights from %s", ckpt_path)
    model.to(device).eval()
    return model


# --------------------------------------------------------------------------- #
# Single-chunk CFM sampler (in normalized space, with temperature).
# --------------------------------------------------------------------------- #

@torch.no_grad()
def diffuse_chunk(
    model: FlowDiT,
    prefix_norm: torch.Tensor,
    *,
    n_steps: int,
    solver: str,
    temperature: float,
    init_noise: Optional[torch.Tensor] = None,
) -> torch.Tensor:
    """Generate one chunk (`block_size` tokens) given a clean *normalized* prefix.

    Args:
        model: trained FlowDiT (eval mode).
        prefix_norm: `[1, P, latent_dim]` already in normalized space.
        n_steps: number of ODE integration steps.
        solver: 'euler' | 'heun'.
        temperature: scales the predicted velocity each step
            (`x <- x - (dt / temperature) * v`). 1.0 = standard rectified-flow
            ODE; <1 sharpens; >1 diffuses.
        init_noise: optional `[1, block_size, latent_dim]` to start from
            (otherwise sampled from `N(0, I)` per call).

    Returns:
        `[1, block_size, latent_dim]` newly generated chunk in **normalized**
        space (caller denormalizes before feeding to the codec).
    """
    device = next(model.parameters()).device
    dtype = next(model.parameters()).dtype
    B = prefix_norm.shape[0]
    P = prefix_norm.shape[1]
    bs = model.block_size
    L = P + bs
    if L > model.max_seq_len:
        raise ValueError(f"context (P={P}) + block ({bs}) exceeds max_seq_len={model.max_seq_len}")

    if init_noise is None:
        target = torch.randn(B, bs, model.latent_dim, device=device, dtype=dtype)
    else:
        target = init_noise.to(device=device, dtype=dtype)

    x = torch.cat([prefix_norm, target], dim=1)
    attn_mask = block_causal_mask(L, model.block_size, device=device).to(dtype)

    def t_per_token(t_now: float) -> torch.Tensor:
        # Prefix kept clean (t=0); only the new chunk carries noise level t_now.
        is_target = torch.arange(L, device=device) >= P
        return is_target.float().unsqueeze(0).expand(B, -1) * t_now

    inv_temp = 1.0 / max(1e-6, float(temperature))
    dt = 1.0 / n_steps
    for k in range(n_steps):
        t_now = 1.0 - k * dt
        t_next = max(0.0, t_now - dt)

        if solver == "euler":
            v = model(x, t_per_token(t_now), attn_mask=attn_mask)
            x = x.clone()
            x[:, P:] = x[:, P:] - dt * inv_temp * v[:, P:]
        elif solver == "heun":
            v1 = model(x, t_per_token(t_now), attn_mask=attn_mask)
            x_pred = x.clone()
            x_pred[:, P:] = x_pred[:, P:] - dt * inv_temp * v1[:, P:]
            v2 = model(x_pred, t_per_token(t_next), attn_mask=attn_mask)
            x = x.clone()
            x[:, P:] = x[:, P:] - 0.5 * dt * inv_temp * (v1[:, P:] + v2[:, P:])
        else:
            raise ValueError(f"unknown solver: {solver!r} (expected 'euler' or 'heun')")

    return x[:, P:]


# --------------------------------------------------------------------------- #
# Audio buffer (thread-safe, O(1) status tracking).
# --------------------------------------------------------------------------- #

class AudioBuffer:
    """Bridges variable-size decoded chunks to fixed-size sounddevice callbacks.

    Also maintains a fixed-size ring of *recently-played* mono samples so the
    GUI can visualise what the user is actually hearing (not what is queued).
    """

    # ~2 s at 48 kHz of mono playback history is enough for any visualiser.
    _RECENT_RING_SAMPLES = 96_000

    def __init__(self, channels: int = 2):
        self._lock = threading.Lock()
        self._chunks: collections.deque = collections.deque()
        self._offset = 0
        self._channels = int(channels)
        self._buffered = 0
        self.underruns = 0
        self.total_samples = 0
        # Recent-playback ring (mono mix). Written every `pull()`.
        self._recent = np.zeros(self._RECENT_RING_SAMPLES, dtype=np.float32)
        self._recent_idx = 0  # next write position (wraps)

    def push(self, audio: np.ndarray) -> None:
        if audio.ndim == 1:
            audio = np.stack([audio, audio], axis=-1)
        with self._lock:
            self._chunks.append(audio.astype(np.float32, copy=False))
            self.total_samples += len(audio)
            self._buffered += len(audio)

    def pull(self, frames: int) -> np.ndarray:
        out = np.zeros((frames, self._channels), dtype=np.float32)
        filled = 0
        with self._lock:
            while filled < frames and self._chunks:
                chunk = self._chunks[0]
                avail = len(chunk) - self._offset
                take = min(avail, frames - filled)
                out[filled: filled + take] = chunk[self._offset: self._offset + take]
                self._offset += take
                filled += take
                if self._offset >= len(chunk):
                    self._chunks.popleft()
                    self._offset = 0
            self._buffered = max(0, self._buffered - filled)
            if filled < frames:
                self.underruns += 1
            # Mirror the audio that just went out into the recent ring (mono mix).
            if filled > 0:
                mono = out[:filled].mean(axis=1) if out.shape[1] > 1 else out[:filled, 0]
                ring = self._recent
                ring_n = ring.shape[0]
                idx = self._recent_idx
                end = idx + filled
                if end <= ring_n:
                    ring[idx:end] = mono
                else:
                    first = ring_n - idx
                    ring[idx:] = mono[:first]
                    ring[: end - ring_n] = mono[first:]
                self._recent_idx = end % ring_n
        return out

    @property
    def buffered_samples(self) -> int:
        return max(0, self._buffered)

    def recent_waveform(self, n: int) -> np.ndarray:
        """Return the last `n` mono samples that were actually played.

        Cheap O(n) read; safe to call from another thread.
        """
        with self._lock:
            ring = self._recent
            ring_n = ring.shape[0]
            n = max(0, min(int(n), ring_n))
            if n == 0:
                return np.zeros(0, dtype=np.float32)
            idx = self._recent_idx
            start = (idx - n) % ring_n
            if start + n <= ring_n:
                return ring[start: start + n].copy()
            first = ring_n - start
            out = np.empty(n, dtype=np.float32)
            out[:first] = ring[start:]
            out[first:] = ring[: n - first]
            return out

    def clear(self) -> None:
        with self._lock:
            self._chunks.clear()
            self._offset = 0
            self._buffered = 0


# --------------------------------------------------------------------------- #
# Keyboard controls (POSIX cbreak; non-blocking via select).
# --------------------------------------------------------------------------- #

class KeyboardController:
    """Non-blocking keyboard input for live parameter adjustment."""

    HELP_LINES = [
        "Keyboard controls:",
        "  q         - quit",
        "  1/2/3     - diffusion steps (4/8/16)",
        "  e/h       - solver (euler / heun)",
        "  +/-       - context chunks (+/- 4)",
        "  </>       - temperature (-/+ 0.1)",
        "  r         - reset to defaults (incl. summary controls)",
        "  x         - crossfade to new random seed",
        "  X         - hard cut to new random seed",
        "  s         - crossfade to specific seed",
        "  S         - hard cut to specific seed",
        "  a         - toggle auto-cycle seeds",
        "  A         - set auto-cycle interval (chunks)",
        "  [ / ]     - crossfade length (-/+ 1 chunk)",
        "  -- summary-latent control (per-chunk, 8 tokens) --",
        "  b / B     - summary bias  -/+ (uniform across all 8 tokens)",
        "  g / G     - summary scale -/+ (uniform across all 8 tokens)",
        "  i         - per-token edit (e.g. 'b3 0.5' or 's7 1.20')",
        "  o         - reset summary controls only (scale=1, bias=0)",
        "  n         - randomize summary bias  (uniform in bias range)",
        "  N         - randomize summary scale (uniform in scale range)",
        "  m         - randomize BOTH summary scale & bias",
        "  -- channel-latent control (per-chunk, 64 feature dims) --",
        "  y         - randomize channel bias  (uniform, independent per dim)",
        "  Y         - randomize channel scale (uniform, independent per dim)",
        "  u         - randomize BOTH channel scale & bias",
        "  U         - reset channel controls only (scale=1, bias=0)",
        "  ?         - show this help",
    ]

    def __init__(self):
        self._old = termios.tcgetattr(sys.stdin)
        tty.setcbreak(sys.stdin.fileno())
        self._seed_mode = False
        self._seed_buf = ""
        self._seed_action: Optional[str] = None
        self._summary_mode = False
        self._summary_buf = ""
        print()
        for line in self.HELP_LINES:
            print(line)
        print("-" * 40)

    def close(self) -> None:
        try:
            termios.tcsetattr(sys.stdin, termios.TCSADRAIN, self._old)
        except Exception:
            pass

    def __del__(self):  # best-effort restore
        self.close()

    def poll(self) -> Optional[str]:
        if select.select([sys.stdin], [], [], 0) == ([sys.stdin], [], []):
            return sys.stdin.read(1)
        return None

    def apply_key(self, key: str, gen: "RealtimeFlowGenerator") -> bool:
        """Apply a single keypress. Returns False if the user requested quit."""
        if self._seed_mode:
            return self._apply_seed_input(key, gen)
        if self._summary_mode:
            return self._apply_summary_input(key, gen)

        if key == "q":
            return False

        # Diffusion steps
        if key in {"1", "2", "3"}:
            steps = {"1": 4, "2": 8, "3": 16}[key]
            gen.n_steps = steps
            print(f"[KEY] diffusion steps = {steps}")
        # Solver
        elif key in {"e", "h"}:
            solver = {"e": "euler", "h": "heun"}[key]
            gen.solver = solver
            print(f"[KEY] solver = {solver}")
        # Context length (in chunks)
        elif key == "+":
            gen.set_context_chunks(min(gen.max_context_chunks, gen.context_chunks + 4))
            print(f"[KEY] context_chunks = {gen.context_chunks}")
        elif key == "-":
            gen.set_context_chunks(max(0, gen.context_chunks - 4))
            print(f"[KEY] context_chunks = {gen.context_chunks}")
        # Temperature
        elif key == ">":
            gen.temperature = min(2.0, gen.temperature + 0.1)
            print(f"[KEY] temperature = {gen.temperature:.2f}")
        elif key == "<":
            gen.temperature = max(0.1, gen.temperature - 0.1)
            print(f"[KEY] temperature = {gen.temperature:.2f}")
        # Reset
        elif key == "r":
            gen.n_steps = 4
            gen.solver = "euler"
            gen.temperature = 1.0
            gen.set_context_chunks(gen.default_context_chunks)
            gen.summary_scale = torch.ones(
                gen.block_size, device=gen.device, dtype=torch.float32
            )
            gen.summary_bias = torch.zeros(
                gen.block_size, device=gen.device, dtype=torch.float32
            )
            gen.channel_scale = torch.ones(
                gen.latent_dim, device=gen.device, dtype=torch.float32
            )
            gen.channel_bias = torch.zeros(
                gen.latent_dim, device=gen.device, dtype=torch.float32
            )
            print("[KEY] reset to defaults (incl. summary & channel controls)")
        # Seed changes
        elif key == "x":
            gen.crossfade_to_random()
        elif key == "X":
            gen.restart()
        elif key == "s":
            self._begin_seed_input("crossfade")
        elif key == "S":
            self._begin_seed_input("hardcut")
        # Crossfade length
        elif key == "]":
            gen.crossfade_chunks = min(16, gen.crossfade_chunks + 1)
            print(f"[KEY] crossfade length = {gen.crossfade_chunks} chunks")
        elif key == "[":
            gen.crossfade_chunks = max(1, gen.crossfade_chunks - 1)
            print(f"[KEY] crossfade length = {gen.crossfade_chunks} chunks")
        # Auto-cycle
        elif key == "a":
            gen.auto_cycle_enabled = not gen.auto_cycle_enabled
            status = "ENABLED" if gen.auto_cycle_enabled else "DISABLED"
            print(f"[KEY] auto-cycle {status} (every {gen.auto_cycle_interval} chunks)")
        elif key == "A":
            self._begin_seed_input("auto_cycle")
        # Summary-latent control (uniform nudges)
        elif key == "b":
            gen.adjust_summary_bias(-gen.summary_bias_step)
        elif key == "B":
            gen.adjust_summary_bias(+gen.summary_bias_step)
        elif key == "g":
            gen.adjust_summary_scale(-gen.summary_scale_step)
        elif key == "G":
            gen.adjust_summary_scale(+gen.summary_scale_step)
        elif key == "i":
            self._begin_summary_edit(gen)
        elif key == "o":
            gen.reset_summary_control()
        elif key == "n":
            gen.randomize_summary_bias()
        elif key == "N":
            gen.randomize_summary_scale()
        elif key == "m":
            gen.randomize_summary_both()
        # Channel-latent control (per-channel over `latent_dim` feature dims)
        elif key == "y":
            gen.randomize_channel_bias()
        elif key == "Y":
            gen.randomize_channel_scale()
        elif key == "u":
            gen.randomize_channel_both()
        elif key == "U":
            gen.reset_channel_control()
        elif key == "?":
            print()
            for line in self.HELP_LINES:
                print(line)
            print("-" * 40)
        return True

    def _begin_seed_input(self, action: str) -> None:
        self._seed_mode = True
        self._seed_buf = ""
        self._seed_action = action
        prompt = (
            "[AUTO-CYCLE] Enter interval (chunks): "
            if action == "auto_cycle"
            else "[SEED] Enter seed (digits + Enter, Esc to cancel): "
        )
        sys.stdout.write(prompt)
        sys.stdout.flush()

    def _apply_seed_input(self, key: str, gen: "RealtimeFlowGenerator") -> bool:
        if key in "0123456789":
            self._seed_buf += key
            sys.stdout.write(key)
            sys.stdout.flush()
        elif key in ("\x7f", "\x08") and self._seed_buf:  # backspace
            self._seed_buf = self._seed_buf[:-1]
            sys.stdout.write("\b \b")
            sys.stdout.flush()
        elif key in ("\r", "\n"):  # enter
            print()
            if self._seed_buf:
                try:
                    n = int(self._seed_buf)
                    if self._seed_action == "auto_cycle":
                        if n > 0:
                            gen.auto_cycle_interval = n
                            gen.auto_cycle_enabled = True
                            print(f"[AUTO-CYCLE] Enabled with interval {n} chunks")
                        else:
                            print("[AUTO-CYCLE] Invalid interval")
                    elif self._seed_action == "crossfade":
                        gen.crossfade_to_seed(n % (2**31))
                    else:
                        gen.set_seed(n % (2**31))
                except ValueError:
                    print("[SEED] Invalid number")
            else:
                print("[SEED] Cancelled")
            self._reset_seed_mode()
        elif key == "\x1b":  # escape
            print("\n[SEED] Cancelled")
            self._reset_seed_mode()
        return True

    def _reset_seed_mode(self) -> None:
        self._seed_mode = False
        self._seed_buf = ""
        self._seed_action = None

    # ----- summary-latent edit input ----- #

    def _begin_summary_edit(self, gen: "RealtimeFlowGenerator") -> None:
        """Enter the per-token summary-control edit prompt.

        Format: ``<kind><idx> <value>`` where ``kind`` is ``b`` (bias) or
        ``s``/``g`` (scale), ``idx`` is in [0, block_size), and ``value`` is
        a float. Examples: ``b3 0.5``, ``s7 1.20``, ``g0 -0.10``.
        """
        self._summary_mode = True
        self._summary_buf = ""
        sys.stdout.write(
            "[SUMMARY] Edit one token. Format: <b|s><idx> <value> "
            f"(idx 0..{gen.block_size - 1}). Enter to apply, Esc to cancel: "
        )
        sys.stdout.flush()

    def _apply_summary_input(self, key: str, gen: "RealtimeFlowGenerator") -> bool:
        # Allowed: digits, kind letters, sign, decimal, space, scientific 'e'.
        if key in "0123456789bBsSgG .-+eE":
            self._summary_buf += key
            sys.stdout.write(key)
            sys.stdout.flush()
        elif key in ("\x7f", "\x08") and self._summary_buf:  # backspace
            self._summary_buf = self._summary_buf[:-1]
            sys.stdout.write("\b \b")
            sys.stdout.flush()
        elif key in ("\r", "\n"):  # enter
            print()
            txt = self._summary_buf.strip()
            if txt:
                try:
                    parts = txt.split()
                    if len(parts) != 2:
                        raise ValueError("need exactly two whitespace-separated fields")
                    tok, val = parts
                    if len(tok) < 2 or not tok[0].lower() in {"b", "s", "g"}:
                        raise ValueError("first field must be <kind><idx>, e.g. b3")
                    kind = tok[0].lower()
                    idx = int(tok[1:])
                    value = float(val)
                    gen.set_summary_token(idx, kind, value)
                except Exception as e:
                    print(f"[SUMMARY] Parse error: {e}")
            else:
                print("[SUMMARY] Cancelled")
            self._reset_summary_mode()
        elif key == "\x1b":  # escape
            print("\n[SUMMARY] Cancelled")
            self._reset_summary_mode()
        return True

    def _reset_summary_mode(self) -> None:
        self._summary_mode = False
        self._summary_buf = ""


# --------------------------------------------------------------------------- #
# Realtime generator
# --------------------------------------------------------------------------- #

class RealtimeFlowGenerator:
    """Generates audio chunk-by-chunk and streams it to the speakers."""

    def __init__(
        self,
        model: FlowDiT,
        codec: CodecWrapper,
        device: torch.device,
        *,
        n_steps: int = 4,
        solver: str = "euler",
        temperature: float = 1.0,
        seed_scale: float = 0.0,
        context_chunks: int = 32,
        prebuffer_chunks: int = 2,
        crossfade_chunks: int = 4,
        initial_seed: Optional[int] = None,
    ):
        self.model = model
        self.codec = codec
        self.device = device
        self.dtype = next(model.parameters()).dtype

        self.n_steps = int(n_steps)
        self.solver = str(solver)
        self.temperature = float(temperature)
        self.seed_scale = float(seed_scale)

        # Context (sliding window) sizing -- in chunks, converted to tokens
        # via model.block_size. The hard ceiling is `max_seq_len // block_size
        # - 1` (one slot reserved for the new chunk).
        # `context_chunks <= 0` is treated as a sentinel meaning "use the
        # maximum safe context the model supports".
        self.block_size: int = model.block_size
        self.latent_dim: int = model.latent_dim
        self.max_context_chunks: int = max(0, model.max_seq_len // self.block_size - 1)
        if int(context_chunks) <= 0:
            self.default_context_chunks: int = self.max_context_chunks
        else:
            self.default_context_chunks = int(context_chunks)
        self.context_chunks: int = min(self.default_context_chunks, self.max_context_chunks)
        self.context_tokens: int = self.context_chunks * self.block_size

        self.sample_rate: int = codec.sample_rate
        self.tokens_per_chunk: int = codec.tokens_per_chunk
        self.samples_per_chunk: int = codec.samples_per_chunk

        self.prebuffer_chunks = int(prebuffer_chunks)
        self.crossfade_chunks = int(crossfade_chunks)

        # Sliding-window prefix in the model's *normalized* space (so we don't
        # re-normalize every chunk). Empty -> unconditional generation.
        self.prefix_norm: torch.Tensor = torch.zeros(
            1, 0, self.latent_dim, device=self.device, dtype=self.dtype
        )

        # Summary-latent controls. The flow model emits `block_size` tokens
        # per chunk in the model's normalized (~unit Gaussian) space; these
        # are the "summary latents" for one ~683 ms window of audio. The user
        # can bias and/or scale each of the 8 tokens independently in real
        # time. Modulation is applied AFTER diffusion and BEFORE both decode
        # and prefix-append, so the effect is audible and also conditions
        # subsequent generation through the rolling prefix.
        #
        #   chunk_norm[:, i, :] <- chunk_norm[:, i, :] * scale[i] + bias[i]
        #
        # Defaults are scale=1.0, bias=0.0 (identity / no-op fast path).
        self.summary_scale: torch.Tensor = torch.ones(
            self.block_size, device=self.device, dtype=torch.float32
        )
        self.summary_bias: torch.Tensor = torch.zeros(
            self.block_size, device=self.device, dtype=torch.float32
        )
        # Step sizes for keyboard nudges (per-token uniform deltas).
        self.summary_scale_step: float = 0.05
        self.summary_bias_step: float = 0.05
        # Soft clamps to keep manual edits in a sane range. They don't bound
        # values set programmatically via `set_summary_token` (which is the
        # explicit-edit path) but they do bound the +/- nudge keys.
        self.summary_scale_range: tuple[float, float] = (0.05, 4.0)
        self.summary_bias_range: tuple[float, float] = (-3.0, 3.0)

        # Per-channel (latent-dim) controls. These are orthogonal to the
        # summary (per-token) controls above: they modulate each of the
        # `latent_dim` feature channels uniformly across all `block_size`
        # tokens. Applied AFTER the summary control, so both can compose.
        #
        #   chunk_norm[:, :, d] <- chunk_norm[:, :, d] * cscale[d] + cbias[d]
        #
        # Defaults are identity (1.0 / 0.0) so this is a no-op fast path.
        self.channel_scale: torch.Tensor = torch.ones(
            self.latent_dim, device=self.device, dtype=torch.float32
        )
        self.channel_bias: torch.Tensor = torch.zeros(
            self.latent_dim, device=self.device, dtype=torch.float32
        )
        self.channel_scale_range: tuple[float, float] = (0.05, 4.0)
        self.channel_bias_range: tuple[float, float] = (-3.0, 3.0)

        self.audio_buffer = AudioBuffer(channels=2)
        # Streaming wav writer (opened lazily in run() when --save is set);
        # avoids accumulating an unbounded list of chunks for infinite runs.
        self._save_writer = None
        self._save_path: Optional[str] = None
        self.chunk_count = 0
        self.total_audio_samples = 0
        self.total_compute_time = 0.0
        self.gen_times: List[float] = []
        self.decode_times: List[float] = []
        # Robustness counters for long-running operation.
        self._consecutive_errors: int = 0
        self._nan_recoveries: int = 0
        self._cache_release_every: int = 100

        # Seed tracking
        self.current_seed: Optional[int] = None
        if initial_seed is not None:
            self._apply_seed(int(initial_seed))
        else:
            self._set_time_seed()

        # Auto-cycle state
        self.auto_cycle_enabled = False
        self.auto_cycle_interval = 100
        self._auto_cycle_counter = 0

    # ----- seed helpers ----- #

    def _apply_seed(self, seed: int) -> None:
        self.current_seed = int(seed) % (2**31)
        torch.manual_seed(self.current_seed)
        np.random.seed(self.current_seed)
        random.seed(self.current_seed)

    def _set_time_seed(self) -> None:
        self._apply_seed(int(time.time() * 1000) % (2**31))

    def _log_state(self) -> None:
        print(
            f"[STATE] seed={self.current_seed} steps={self.n_steps} solver={self.solver} "
            f"temp={self.temperature:.2f} ctx={self.context_chunks}ch "
            f"({self.context_tokens}tok, ~{self.context_chunks * self.samples_per_chunk / self.sample_rate:.1f}s)"
        )
        if self._summary_active():
            print(
                f"        summary_scale={self._fmt_summary_vec(self.summary_scale)} "
                f"summary_bias={self._fmt_summary_vec(self.summary_bias)}"
            )
        if self._channel_active():
            print(
                f"        channel_scale={self._fmt_channel_vec(self.channel_scale)} "
                f"channel_bias={self._fmt_channel_vec(self.channel_bias)}"
            )

    # ----- summary-latent control ----- #

    def _summary_active(self) -> bool:
        """True if either control deviates from the identity defaults."""
        return bool(
            (self.summary_scale != 1.0).any().item()
            or (self.summary_bias != 0.0).any().item()
        )

    @staticmethod
    def _fmt_summary_vec(v: torch.Tensor) -> str:
        vals = v.detach().cpu().tolist()
        return "[" + ", ".join(f"{x:+.2f}" for x in vals) + "]"

    def _apply_summary_control(self, chunk_norm: torch.Tensor) -> torch.Tensor:
        """Apply per-token scale & bias to the freshly-generated chunk.

        Args:
            chunk_norm: `[1, block_size, latent_dim]` in normalized space.
        Returns:
            Same shape, modulated as `x[:, i, :] = x[:, i, :] * s[i] + b[i]`.
            No-op (identity, no allocation/casts) when controls are at
            defaults to keep the realtime hot path cheap.
        """
        if not self._summary_active():
            return chunk_norm
        s = self.summary_scale.to(device=chunk_norm.device, dtype=chunk_norm.dtype).view(1, -1, 1)
        b = self.summary_bias.to(device=chunk_norm.device, dtype=chunk_norm.dtype).view(1, -1, 1)
        return chunk_norm * s + b

    def adjust_summary_bias(self, delta: float) -> None:
        """Add `delta` to every entry of `summary_bias` (clamped to soft range)."""
        lo, hi = self.summary_bias_range
        self.summary_bias = (self.summary_bias + float(delta)).clamp_(lo, hi)
        print(f"[KEY] summary_bias = {self._fmt_summary_vec(self.summary_bias)}")

    def adjust_summary_scale(self, delta: float) -> None:
        """Add `delta` to every entry of `summary_scale` (clamped to soft range)."""
        lo, hi = self.summary_scale_range
        self.summary_scale = (self.summary_scale + float(delta)).clamp_(lo, hi)
        print(f"[KEY] summary_scale = {self._fmt_summary_vec(self.summary_scale)}")

    def set_summary_token(self, idx: int, kind: str, value: float) -> None:
        """Set one entry of either the scale or bias vector (no clamp).

        Args:
            idx:   Token index in [0, block_size).
            kind:  'b' for bias, 's' or 'g' for scale (gain).
            value: New scalar value for `summary_{bias|scale}[idx]`.
        """
        if not (0 <= idx < self.block_size):
            raise ValueError(f"token idx must be in [0, {self.block_size}); got {idx}")
        kind = str(kind).lower()
        if kind == "b":
            self.summary_bias[idx] = float(value)
            label = "bias"
        elif kind in ("s", "g"):
            self.summary_scale[idx] = float(value)
            label = "scale"
        else:
            raise ValueError(f"kind must be 'b' (bias) or 's'/'g' (scale); got {kind!r}")
        print(f"[KEY] summary {label}[{idx}] = {float(value):+.3f}")
        print(f"        scale = {self._fmt_summary_vec(self.summary_scale)}")
        print(f"        bias  = {self._fmt_summary_vec(self.summary_bias)}")

    def reset_summary_control(self) -> None:
        """Restore identity controls (scale=1, bias=0)."""
        self.summary_scale = torch.ones(
            self.block_size, device=self.device, dtype=torch.float32
        )
        self.summary_bias = torch.zeros(
            self.block_size, device=self.device, dtype=torch.float32
        )
        print("[KEY] summary controls reset (scale=1.0, bias=0.0)")

    def randomize_summary_bias(self) -> None:
        """Sample each bias entry uniformly from `summary_bias_range`."""
        lo, hi = self.summary_bias_range
        self.summary_bias = (
            torch.rand(self.block_size, device=self.device, dtype=torch.float32)
            * (hi - lo)
            + lo
        )
        print(f"[KEY] summary_bias  ~U[{lo:+.2f},{hi:+.2f}] = {self._fmt_summary_vec(self.summary_bias)}")

    def randomize_summary_scale(self) -> None:
        """Sample each scale entry uniformly from `summary_scale_range`."""
        lo, hi = self.summary_scale_range
        self.summary_scale = (
            torch.rand(self.block_size, device=self.device, dtype=torch.float32)
            * (hi - lo)
            + lo
        )
        print(f"[KEY] summary_scale ~U[{lo:+.2f},{hi:+.2f}] = {self._fmt_summary_vec(self.summary_scale)}")

    def randomize_summary_both(self) -> None:
        """Randomize both scale and bias in one shot."""
        self.randomize_summary_scale()
        self.randomize_summary_bias()

    def set_summary_vectors(
        self,
        scale: Optional[List[float] | torch.Tensor] = None,
        bias: Optional[List[float] | torch.Tensor] = None,
    ) -> None:
        """Bulk-set both vectors (used at startup from CLI args)."""
        if scale is not None:
            t = torch.as_tensor(scale, dtype=torch.float32, device=self.device)
            if t.numel() != self.block_size:
                raise ValueError(f"scale must have {self.block_size} elements")
            self.summary_scale = t.clone()
        if bias is not None:
            t = torch.as_tensor(bias, dtype=torch.float32, device=self.device)
            if t.numel() != self.block_size:
                raise ValueError(f"bias must have {self.block_size} elements")
            self.summary_bias = t.clone()

    # ----- channel (latent-dim) control ----- #

    def _channel_active(self) -> bool:
        """True if either channel control deviates from identity defaults."""
        return bool(
            (self.channel_scale != 1.0).any().item()
            or (self.channel_bias != 0.0).any().item()
        )

    @staticmethod
    def _fmt_channel_vec(v: torch.Tensor) -> str:
        """Compact summary stats for a length-D channel vector (D=64 is too
        wide to print in full each chunk)."""
        vals = v.detach().float()
        return (
            f"[D={vals.numel()} "
            f"min={vals.min().item():+.2f} "
            f"max={vals.max().item():+.2f} "
            f"mean={vals.mean().item():+.2f} "
            f"std={vals.std(unbiased=False).item():.2f}]"
        )

    def _apply_channel_control(self, chunk_norm: torch.Tensor) -> torch.Tensor:
        """Apply per-channel scale & bias across all tokens in the chunk.

        Args:
            chunk_norm: `[1, block_size, latent_dim]` in normalized space.
        Returns:
            Same shape, modulated as
            `x[:, :, d] = x[:, :, d] * cscale[d] + cbias[d]`.
            No-op fast path when both vectors are at identity defaults.
        """
        if not self._channel_active():
            return chunk_norm
        s = self.channel_scale.to(device=chunk_norm.device, dtype=chunk_norm.dtype).view(1, 1, -1)
        b = self.channel_bias.to(device=chunk_norm.device, dtype=chunk_norm.dtype).view(1, 1, -1)
        return chunk_norm * s + b

    def reset_channel_control(self) -> None:
        """Restore identity channel controls (scale=1, bias=0)."""
        self.channel_scale = torch.ones(
            self.latent_dim, device=self.device, dtype=torch.float32
        )
        self.channel_bias = torch.zeros(
            self.latent_dim, device=self.device, dtype=torch.float32
        )
        print("[KEY] channel controls reset (scale=1.0, bias=0.0)")

    def randomize_channel_bias(self) -> None:
        """Sample each of the `latent_dim` bias entries uniformly from
        `channel_bias_range` (independently per channel)."""
        lo, hi = self.channel_bias_range
        self.channel_bias = (
            torch.rand(self.latent_dim, device=self.device, dtype=torch.float32)
            * (hi - lo)
            + lo
        )
        print(f"[KEY] channel_bias  ~U[{lo:+.2f},{hi:+.2f}] {self._fmt_channel_vec(self.channel_bias)}")

    def randomize_channel_scale(self) -> None:
        """Sample each of the `latent_dim` scale entries uniformly from
        `channel_scale_range` (independently per channel)."""
        lo, hi = self.channel_scale_range
        self.channel_scale = (
            torch.rand(self.latent_dim, device=self.device, dtype=torch.float32)
            * (hi - lo)
            + lo
        )
        print(f"[KEY] channel_scale ~U[{lo:+.2f},{hi:+.2f}] {self._fmt_channel_vec(self.channel_scale)}")

    def randomize_channel_both(self) -> None:
        """Randomize both channel scale and bias in one shot."""
        self.randomize_channel_scale()
        self.randomize_channel_bias()

    # ----- context (prefix) management ----- #

    def _trim_prefix(self) -> None:
        """Truncate `prefix_norm` to the last `context_tokens` tokens.

        Note: the obvious `prefix[:, -ctx_tokens:]` is wrong when
        `ctx_tokens == 0` because Python's `-0` slice means `[0:]` (the whole
        tensor), which would let the prefix grow unboundedly until it hits
        `max_seq_len`.
        """
        cur = self.prefix_norm.shape[1]
        if cur <= self.context_tokens:
            return
        if self.context_tokens == 0:
            self.prefix_norm = self.prefix_norm[:, :0]
        else:
            self.prefix_norm = self.prefix_norm[:, -self.context_tokens:]

    def set_context_chunks(self, n: int) -> None:
        n = max(0, min(int(n), self.max_context_chunks))
        self.context_chunks = n
        self.context_tokens = n * self.block_size
        # Trim the running prefix immediately so subsequent steps see the new size.
        self._trim_prefix()

    def _append_to_prefix(self, new_chunk_norm: torch.Tensor) -> None:
        """Append `new_chunk_norm` ([1, block_size, D]) to the rolling prefix and trim
        to `context_tokens`."""
        self.prefix_norm = torch.cat([self.prefix_norm, new_chunk_norm], dim=1)
        self._trim_prefix()

    # ----- per-chunk generation ----- #

    def _generate_one_chunk(self) -> torch.Tensor:
        """Run the diffusion sampler to produce one chunk in normalized space.

        Includes a NaN/Inf guard: if numerical drift produces a non-finite
        chunk (most common with extreme temperature or after very long
        runs in bf16), we reset state and retry once; if that still fails,
        we substitute a zero chunk so the codec receives valid input and
        the stream continues with a brief silence rather than crashing.
        """
        # Optional initial noise scaling: shrink the starting noise toward zero
        # to reduce variance (effectively biases the trajectory toward the
        # data manifold's mode).
        if self.seed_scale != 0.0:
            init = torch.randn(
                1, self.block_size, self.latent_dim, device=self.device, dtype=self.dtype
            ) * (1.0 - float(self.seed_scale))
        else:
            init = None
        chunk = diffuse_chunk(
            self.model,
            self.prefix_norm,
            n_steps=self.n_steps,
            solver=self.solver,
            temperature=self.temperature,
            init_noise=init,
        )
        if not torch.isfinite(chunk).all():
            self._nan_recoveries += 1
            logger.warning(
                "non-finite chunk detected (recoveries=%d); resetting state and retrying",
                self._nan_recoveries,
            )
            self._full_reset()
            chunk = diffuse_chunk(
                self.model,
                self.prefix_norm,
                n_steps=self.n_steps,
                solver=self.solver,
                temperature=self.temperature,
                init_noise=None,
            )
            if not torch.isfinite(chunk).all():
                logger.error("non-finite chunk persisted after reset; substituting zeros")
                chunk = torch.zeros_like(chunk)
        # Apply user-controlled summary-latent modulation (no-op at defaults).
        chunk = self._apply_summary_control(chunk)
        # Apply per-channel (latent-dim) modulation after summary control.
        chunk = self._apply_channel_control(chunk)
        return chunk

    def _decode_chunk(self, chunk_norm: torch.Tensor) -> np.ndarray:
        """Denormalize -> codec.decode_next_chunk -> stereo numpy [N, 2]."""
        chunk_raw = self.model.denormalize(chunk_norm)  # [1, block_size, D]
        # decode_next expects [tokens_per_chunk, latent_dim]
        chunk_for_codec = chunk_raw.squeeze(0)  # [block_size, D]
        wv = self.codec.decode_next_chunk(chunk_for_codec)
        # Standardize to [N, 2] stereo float32.
        if wv.ndim == 1:
            wv = np.stack([wv, wv], axis=-1)
        elif wv.ndim == 2 and wv.shape[0] < wv.shape[1]:
            wv = wv.T  # codicodec returns [channels, samples] -> we want [samples, channels]
        return wv.astype(np.float32, copy=False)

    def _step(self):
        t0 = time.time()
        chunk_norm = self._generate_one_chunk()
        t_gen = time.time() - t0

        t1 = time.time()
        audio = self._decode_chunk(chunk_norm)
        t_dec = time.time() - t1

        # Slide the prefix forward AFTER decoding (decode is conditioned on
        # the freshly-generated chunk, then the chunk becomes prefix).
        self._append_to_prefix(chunk_norm)

        self.gen_times.append(t_gen)
        self.decode_times.append(t_dec)
        if len(self.gen_times) > 200:
            self.gen_times = self.gen_times[-200:]
            self.decode_times = self.decode_times[-200:]
        self.chunk_count += 1
        self.total_audio_samples += len(audio)
        self.total_compute_time += t_gen + t_dec
        # Periodically release accelerator cache to prevent fragmentation
        # over very long sessions.
        if self._cache_release_every > 0 and self.chunk_count % self._cache_release_every == 0:
            self._release_device_cache()
        return audio, t_gen, t_dec

    def _release_device_cache(self) -> None:
        """Best-effort allocator cleanup. Safe no-op if the API is missing."""
        try:
            if self.device.type == "mps" and hasattr(torch, "mps") and hasattr(torch.mps, "empty_cache"):
                torch.mps.empty_cache()
            elif self.device.type == "cuda":
                torch.cuda.empty_cache()
        except Exception as e:  # pragma: no cover
            logger.debug("cache release failed (non-fatal): %s", e)

    # ----- state control ----- #

    def _full_reset(self) -> None:
        """Drop all rolling state: codec stream + prefix + timing buffers."""
        self.codec.reset_streaming()
        self.prefix_norm = torch.zeros(
            1, 0, self.latent_dim, device=self.device, dtype=self.dtype
        )
        self.gen_times.clear()
        self.decode_times.clear()
        self.chunk_count = 0
        self._release_device_cache()

    def restart(self) -> None:
        self._set_time_seed()
        self._full_reset()
        self._log_state()

    def set_seed(self, seed: int) -> None:
        self._apply_seed(seed)
        self._full_reset()
        self._log_state()

    def crossfade_to_seed(self, seed: int) -> None:
        n = self.crossfade_chunks
        old_seed = self.current_seed
        secs = n * self.samples_per_chunk / self.sample_rate
        print(f"[XFADE] {old_seed} -> {seed} ({n} chunks, ~{secs:.1f}s)")

        # Render `n` more chunks from the OLD stream (these will be the
        # fade-out source).
        old_chunks: List[np.ndarray] = []
        for _ in range(n):
            chunk_norm = self._generate_one_chunk()
            audio = self._decode_chunk(chunk_norm)
            self._append_to_prefix(chunk_norm)
            old_chunks.append(audio)

        # Hard cut to the new seed. Codec stream is reset so the new chunks
        # are independent.
        self._apply_seed(seed)
        self._full_reset()

        # Render `n` chunks from the NEW stream and crossfade against the
        # corresponding old chunks (equal-power fade).
        for i in range(n):
            chunk_norm = self._generate_one_chunk()
            new_audio = self._decode_chunk(chunk_norm)
            self._append_to_prefix(chunk_norm)
            old_audio = old_chunks[i]
            fade_len = min(len(old_audio), len(new_audio))
            alpha = (i + 1) / n
            fade_out = float(np.cos(alpha * np.pi / 2))
            fade_in = float(np.sin(alpha * np.pi / 2))
            mixed = (
                old_audio[:fade_len] * fade_out
                + new_audio[:fade_len] * fade_in
            )
            mixed = mixed.astype(np.float32)
            self.audio_buffer.push(mixed)
            self._save_chunk(mixed)

        self._log_state()
        print(f"[XFADE] Done -> seed {self.current_seed}")

    def crossfade_to_random(self) -> None:
        self.crossfade_to_seed(random.randint(0, 2**31 - 1))

    def _maybe_auto_cycle(self) -> None:
        if not self.auto_cycle_enabled:
            return
        self._auto_cycle_counter += 1
        if self._auto_cycle_counter >= self.auto_cycle_interval:
            self._auto_cycle_counter = 0
            new_seed = random.randint(0, 2**31 - 1)
            print(
                f"\n[AUTO-CYCLE] {self.current_seed} -> {new_seed} "
                f"(every {self.auto_cycle_interval} chunks)"
            )
            self.crossfade_to_seed(new_seed)

    # ----- main loop ----- #

    def run(self, max_chunks: Optional[int] = None, save_path: Optional[str] = None) -> None:
        self.model.eval()
        self.codec.reset_streaming()
        self._open_save_writer(save_path)

        kbd = KeyboardController()
        try:
            print("\nStarting generation:")
            self._log_state()
            print(f"\nPre-buffering {self.prebuffer_chunks} chunks...")
            for i in range(self.prebuffer_chunks):
                audio, t_gen, t_dec = self._step()
                self.audio_buffer.push(audio)
                self._save_chunk(audio)
                secs = len(audio) / self.sample_rate
                print(
                    f"  Chunk {i}: gen {t_gen*1000:5.0f}ms + dec {t_dec*1000:5.0f}ms "
                    f"-> {len(audio)} samples ({secs:.2f}s)"
                )

            def _callback(outdata, frames, time_info, status):
                outdata[:] = self.audio_buffer.pull(frames)

            chunks_done = self.prebuffer_chunks
            max_buf_secs = 30.0
            throttle_to = 15.0

            with sd.OutputStream(
                samplerate=self.sample_rate,
                channels=2,
                dtype="float32",
                blocksize=2048,
                callback=_callback,
                latency="low",
            ):
                print("\nPlaying... (keyboard controls active)\n")

                while True:
                    key = kbd.poll()
                    if key is not None and not kbd.apply_key(key, self):
                        print("\nQuit requested.")
                        break

                    if max_chunks is not None and chunks_done >= max_chunks:
                        # Drain buffer before stopping.
                        while self.audio_buffer.buffered_samples > 0:
                            time.sleep(0.05)
                        time.sleep(0.3)
                        break

                    # Throttle generation if buffer is too deep.
                    buf_s = self.audio_buffer.buffered_samples / self.sample_rate
                    if buf_s > max_buf_secs:
                        while self.audio_buffer.buffered_samples / self.sample_rate > throttle_to:
                            k = kbd.poll()
                            if k is not None and not kbd.apply_key(k, self):
                                print("\nQuit requested.")
                                kbd.close()
                                return
                            time.sleep(0.05)
                        continue

                    try:
                        audio, t_gen, t_dec = self._step()
                        self._consecutive_errors = 0
                    except KeyboardInterrupt:
                        raise
                    except Exception as e:
                        self._consecutive_errors += 1
                        logger.error(
                            "step %d failed (consecutive=%d): %s",
                            chunks_done + 1, self._consecutive_errors, e,
                            exc_info=True,
                        )
                        if self._consecutive_errors >= 5:
                            print(
                                "\n[ABORT] 5 consecutive step failures; bailing out."
                                " See traceback above."
                            )
                            break
                        # Recover: drop all state, reseed, and continue without
                        # advancing chunks_done. The audio buffer keeps playing
                        # whatever was already prebuffered.
                        self._full_reset()
                        self._set_time_seed()
                        time.sleep(0.05)
                        continue
                    self.audio_buffer.push(audio)
                    self._save_chunk(audio)
                    chunks_done += 1

                    self._maybe_auto_cycle()

                    chunk_secs = len(audio) / self.sample_rate
                    total_t = t_gen + t_dec
                    rtf = total_t / chunk_secs if chunk_secs > 0 else float("inf")
                    tag = "RT" if rtf < 1.0 else "SLOW"
                    sum_marker = "on" if self._summary_active() else "-"
                    ch_marker = "on" if self._channel_active() else "-"
                    print(
                        f"  Chunk {chunks_done:4d} | gen {t_gen*1000:5.0f}ms + "
                        f"dec {t_dec*1000:5.0f}ms = {total_t*1000:5.0f}ms | "
                        f"audio {chunk_secs:.2f}s | RTF {rtf:.2f}x [{tag}] | "
                        f"buf {buf_s:4.1f}s | underruns {self.audio_buffer.underruns} | "
                        f"steps={self.n_steps} solver={self.solver} ctx={self.context_chunks}ch "
                        f"seed={self.current_seed} temp={self.temperature:.2f} "
                        f"sum={sum_marker} ch={ch_marker}"
                    )
        except KeyboardInterrupt:
            print("\n\nStopped by user.")
        finally:
            kbd.close()
            self._close_save_writer()

        self._print_summary()

    # ----- streaming wav save ----- #

    def _open_save_writer(self, save_path: Optional[str]) -> None:
        """Open a streaming WAV writer if `save_path` is provided.

        Writes per-chunk via `_save_chunk()` rather than buffering the entire
        session in memory, so `--save` is safe for indefinite runs.
        """
        self._save_path = save_path
        self._save_writer = None
        if not save_path:
            return
        if sf is None:
            print("WARNING: soundfile not installed; --save will be ignored")
            return
        try:
            os.makedirs(os.path.dirname(save_path) or ".", exist_ok=True)
            self._save_writer = sf.SoundFile(
                save_path, mode="w",
                samplerate=self.sample_rate, channels=2, subtype="FLOAT",
            )
            print(f"[SAVE] Streaming session audio to {save_path}")
        except Exception as e:
            logger.error("failed to open save file %s: %s", save_path, e)
            self._save_writer = None

    def _save_chunk(self, audio: np.ndarray) -> None:
        if self._save_writer is None:
            return
        try:
            # SoundFile.write expects [frames, channels] float32.
            self._save_writer.write(audio.astype(np.float32, copy=False))
        except Exception as e:
            logger.error("save write failed (closing writer): %s", e)
            self._close_save_writer()

    def _close_save_writer(self) -> None:
        if self._save_writer is None:
            return
        try:
            frames = self._save_writer.frames
            self._save_writer.close()
            secs = frames / self.sample_rate
            print(f"Saved {secs:.1f}s of audio -> {self._save_path}")
        except Exception as e:
            logger.error("save close failed: %s", e)
        finally:
            self._save_writer = None

    # ----- summary ----- #

    def _print_summary(self) -> None:
        if not self.gen_times:
            return
        avg_gen = float(np.mean(self.gen_times)) * 1000.0
        avg_dec = float(np.mean(self.decode_times)) * 1000.0
        total_audio = self.total_audio_samples / self.sample_rate
        total_compute = self.total_compute_time
        rtf = total_compute / total_audio if total_audio > 0 else float("inf")
        bar = "=" * 60
        print(f"\n{bar}")
        print("  Session Summary")
        print(bar)
        print(f"  Chunks         : {self.chunk_count}")
        print(f"  Total audio    : {total_audio:.1f}s")
        print(f"  Total compute  : {total_compute:.1f}s")
        rt_label = "real-time" if rtf < 1.0 else "slower than real-time"
        print(f"  Overall RTF    : {rtf:.2f}x ({rt_label})")
        print(f"  Avg gen/chunk  : {avg_gen:.0f}ms")
        print(f"  Avg dec/chunk  : {avg_dec:.0f}ms")
        print(f"  Underruns      : {self.audio_buffer.underruns}")
        print(f"  NaN recoveries : {self._nan_recoveries}")
        print(bar)


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #

def _build_argparser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Real-time streaming generation: FlowDiT + CoDiCodec.decode_next().",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument("--ckpt", required=True, help="Path to last.pt or ema.pt produced by training.")
    p.add_argument("--use-ema", action="store_true",
                   help="Load EMA weights from the checkpoint (recommended for inference).")

    # Diffusion / sampler
    p.add_argument("--nfe", type=int, default=4, dest="n_steps",
                   help="Number of ODE steps per chunk.")
    p.add_argument("--solver", default="euler", choices=["euler", "heun"],
                   help="ODE solver. heun is 2x more accurate but 2x slower.")
    p.add_argument("--temperature", type=float, default=1.0,
                   help="Velocity scaling. <1 sharpens, >1 diffuses.")
    p.add_argument("--seed-scale", type=float, default=0.0,
                   help="Shrink initial noise toward 0 (0 = standard N(0, I)).")

    # Streaming / context
    p.add_argument("--context-chunks", type=int, default=32,
                   help="Sliding-window context length, in codec chunks "
                        "(1 chunk ≈ 0.683 s @ 48 kHz). Pass <=0 to use the "
                        "model's maximum safe context (max_seq_len // "
                        "block_size - 1).")
    p.add_argument("--prebuffer", type=int, default=2,
                   help="Number of chunks to render before starting playback.")
    p.add_argument("--crossfade-chunks", type=int, default=4,
                   help="Default crossfade length when switching seeds.")

    # Run control
    p.add_argument("--max-chunks", type=int, default=None,
                   help="Stop after this many chunks (default: run until 'q').")
    p.add_argument("--save", type=str, default=None,
                   help="Optional path to save the full session as a .wav file.")
    p.add_argument("--seed", type=int, default=None,
                   help="Initial RNG seed (default: time-based).")
    p.add_argument("--device", default=None,
                   help="cuda | mps | cpu (default: auto-detect).")

    # Summary-latent control (per-chunk, block_size tokens). Modulates each
    # chunk in normalized space:  x[:, i, :] <- x[:, i, :] * scale[i] + bias[i].
    # Pass either a single float (broadcast to all 8 tokens) or 8 comma-
    # separated floats. These can be adjusted live via b/B, g/G, i, o keys.
    p.add_argument("--summary-scale", type=str, default="1.0",
                   help="Initial per-token scale for the chunk's summary latents. "
                        "Scalar broadcasts to all tokens; or pass 8 comma-separated "
                        "floats. Default 1.0 (identity).")
    p.add_argument("--summary-bias", type=str, default="0.0",
                   help="Initial per-token bias (added in normalized space) for "
                        "the chunk's summary latents. Same format as --summary-scale. "
                        "Default 0.0.")
    return p


def main() -> None:
    args = _build_argparser().parse_args()
    device = best_device(args.device)
    logger.info("device=%s", device)

    ckpt_path = str(Path(args.ckpt).expanduser().resolve())
    if not os.path.exists(ckpt_path):
        raise FileNotFoundError(f"checkpoint not found: {ckpt_path}")

    model = load_model(ckpt_path, device, use_ema=bool(args.use_ema))
    n_params = sum(p.numel() for p in model.parameters())
    logger.info("Model: %d params (%.2fM)", n_params, n_params / 1e6)

    codec = CodecWrapper(CodecConfig(device=str(device)))
    chunk_secs = codec.samples_per_chunk / codec.sample_rate
    logger.info(
        "Codec: chunk=%.3fs, block_size=%d tokens, latent_dim=%d",
        chunk_secs, model.block_size, model.latent_dim,
    )

    generator = RealtimeFlowGenerator(
        model=model,
        codec=codec,
        device=device,
        n_steps=args.n_steps,
        solver=args.solver,
        temperature=args.temperature,
        seed_scale=args.seed_scale,
        context_chunks=args.context_chunks,
        prebuffer_chunks=args.prebuffer,
        crossfade_chunks=args.crossfade_chunks,
        initial_seed=args.seed,
    )

    # Apply optional initial summary-latent controls from CLI.
    bs = generator.block_size
    init_scale = _parse_summary_vec(args.summary_scale, bs, "summary-scale")
    init_bias = _parse_summary_vec(args.summary_bias, bs, "summary-bias")
    generator.set_summary_vectors(scale=init_scale, bias=init_bias)
    if generator._summary_active():
        logger.info(
            "summary control: scale=%s bias=%s",
            generator._fmt_summary_vec(generator.summary_scale),
            generator._fmt_summary_vec(generator.summary_bias),
        )

    generator.run(max_chunks=args.max_chunks, save_path=args.save)


if __name__ == "__main__":
    main()
